services:
  - type: web
    name: alexia-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host=0.0.0.0 --port=10000
    envVars:
      - key: OPENAI_API_KEY
        sync: false
